apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql.yaml
  - postgresql-dev.yaml
  - postgres-exporter.yaml
  - postgres-exporter-read-0.yaml
  - postgres-exporter-read-1.yaml
