apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Gitea Runner
  - deployment.yaml
  
  # Gitea Backup
  - backup-cronjob.yaml
  - create-bucket-job.yaml

namespace: gitea
