apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Repositories (disabled - contains secrets, managed manually)
  # - repositories.yaml
  
  # Applications
  - applications/
