apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus.yaml
  - alertmanager.yaml
  - grafana.yaml
  - kube-state-metrics.yaml
  - node-exporter.yaml
  - kubernetes-dashboard.yaml
  - homer.yaml
  - loki.yaml
  - promtail.yaml
  - reloader.yaml
  - pgweb.yaml
