apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jovies.yaml
  - jovies-dev.yaml
  - portfolio.yaml
  - portfolio-dev.yaml
  - todo.yaml
  - todo-dev.yaml
  - jaejadle.yaml
  - jaejadle-dev.yaml
  - joossam.yaml
  - joossam-dev.yaml
