apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mysql

resources:
  - namespace.yaml
  - storage.yaml
  - configmap.yaml
  - secret.yaml
  - mysql-primary.yaml
  - mysql-replicas.yaml
  - mysql-dev.yaml
  - orchestrator-config.yaml
  - orchestrator-deployment.yaml
  - proxysql-config.yaml
  - proxysql-deployment.yaml
  - mysql-backup-cronjob.yaml
